package myWordlePackage;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ntsak
 */
public class WordleInterface extends javax.swing.JFrame {

    /**
     * Creates new form WordleInterface
     */
    WordleLogic wl = new WordleLogic();
    String word = wl.readWord();
    int remainingChances = 6;
    int Score = 500;
    
    WordleInterface() {
        
        
        initComponents();
        frmLogin.setSize(450,400);
        frmLogin.setLocationRelativeTo(null);
        frmLogin.setVisible(true);
        
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmLogin = new javax.swing.JFrame();
        txfUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pasUserPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnNoAcc = new javax.swing.JButton();
        frmRegister = new javax.swing.JFrame();
        txfUNameRegister = new javax.swing.JTextField();
        pasUPassRegi = new javax.swing.JPasswordField();
        pasUPassConfirmRegi = new javax.swing.JPasswordField();
        lblEntUsername = new javax.swing.JLabel();
        lblEntPassword = new javax.swing.JLabel();
        lblConPassword = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        frmScore = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        txfUserNameScore = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfUserScore = new javax.swing.JTextField();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        txaWordleOutput = new javax.swing.JTextArea();
        txfWordleInput = new javax.swing.JTextField();
        btnCheckWord = new javax.swing.JButton();

        lblUsername.setText("Username:");

        lblPassword.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnNoAcc.setText("No account");
        btnNoAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmLoginLayout = new javax.swing.GroupLayout(frmLogin.getContentPane());
        frmLogin.getContentPane().setLayout(frmLoginLayout);
        frmLoginLayout.setHorizontalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pasUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txfUsername)
                        .addComponent(lblPassword)
                        .addComponent(lblUsername))
                    .addComponent(btnNoAcc))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        frmLoginLayout.setVerticalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNoAcc)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        txfUNameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUNameRegisterActionPerformed(evt);
            }
        });

        lblEntUsername.setText("Enter Username:");

        lblEntPassword.setText("Enter Password:");

        lblConPassword.setText("Confirm Password:");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmRegisterLayout = new javax.swing.GroupLayout(frmRegister.getContentPane());
        frmRegister.getContentPane().setLayout(frmRegisterLayout);
        frmRegisterLayout.setHorizontalGroup(
            frmRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRegisterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(frmRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pasUPassRegi)
                        .addComponent(txfUNameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addComponent(pasUPassConfirmRegi))
                    .addComponent(lblConPassword)
                    .addComponent(lblEntPassword)
                    .addComponent(lblEntUsername)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        frmRegisterLayout.setVerticalGroup(
            frmRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRegisterLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblEntUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfUNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblEntPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasUPassRegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblConPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasUPassConfirmRegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setText("Score");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txfUserNameScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUserNameScoreActionPerformed(evt);
            }
        });

        jLabel2.setText("Username");

        txfUserScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUserScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmScoreLayout = new javax.swing.GroupLayout(frmScore.getContentPane());
        frmScore.getContentPane().setLayout(frmScoreLayout);
        frmScoreLayout.setHorizontalGroup(
            frmScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmScoreLayout.createSequentialGroup()
                .addGroup(frmScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmScoreLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(frmScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfUserScore, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txfUserNameScore)))
                    .addGroup(frmScoreLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        frmScoreLayout.setVerticalGroup(
            frmScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmScoreLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfUserNameScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfUserScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(48, 48, 48))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnG.setText("G");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnH.setText("H");
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });

        btnI.setText("I");
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnJ.setText("J");
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });

        btnK.setText("K");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });

        btnL.setText("L");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        btnM.setText("M");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnN.setText("N");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnO.setText("O");
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        btnP.setText("P");
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnQ.setText("Q");
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });

        btnR.setText("R");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btnS.setText("S");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnT.setText("T");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        btnU.setText("U");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnV.setText("V");
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        btnW.setText("W");
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnY.setText("Y");
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        btnZ.setText("Z");
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });

        txaWordleOutput.setColumns(20);
        txaWordleOutput.setRows(5);

        btnCheckWord.setText("Check");
        btnCheckWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txaWordleOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(btnCheckWord, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(txfWordleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txfWordleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txaWordleOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnCheckWord)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF)
                    .addComponent(btnI)
                    .addComponent(btnG)
                    .addComponent(btnH)
                    .addComponent(btnD)
                    .addComponent(btnE)
                    .addComponent(btnC)
                    .addComponent(btnB)
                    .addComponent(btnA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJ)
                    .addComponent(btnK)
                    .addComponent(btnL)
                    .addComponent(btnM)
                    .addComponent(btnN)
                    .addComponent(btnO)
                    .addComponent(btnP)
                    .addComponent(btnQ)
                    .addComponent(btnR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnS)
                    .addComponent(btnT)
                    .addComponent(btnU)
                    .addComponent(btnV)
                    .addComponent(btnW)
                    .addComponent(btnX)
                    .addComponent(btnY)
                    .addComponent(btnZ))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "A");
        }
    }//GEN-LAST:event_btnAActionPerformed

    private void txfUNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUNameRegisterActionPerformed

    }//GEN-LAST:event_txfUNameRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String login = wl.Login(txfUsername.getText(), pasUserPassword.getText());

        if (login.equals("Correct")) {

            this.setVisible(true);
            this.setLocationRelativeTo(null);
            frmLogin.setVisible(false);

        } else if (login.equals("Incorrect")) {

            JOptionPane.showMessageDialog(this, "Incorrect Password");

        } else if (login.equals("UserNotFound")) {

            JOptionPane.showMessageDialog(this, "User does not exist. \nPlease Register if you have no account");

        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed

        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "B");
        }
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "C");
        }
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "D");
        }
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "E");
        }
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "F");
        }
    }//GEN-LAST:event_btnFActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "I");
        }
    }//GEN-LAST:event_btnIActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "G");
        }
    }//GEN-LAST:event_btnGActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "H");
        }
    }//GEN-LAST:event_btnHActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "J");
        }
    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "K");
        }
    }//GEN-LAST:event_btnKActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "L");
        }
    }//GEN-LAST:event_btnLActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "M");
        }
    }//GEN-LAST:event_btnMActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "N");
        }
    }//GEN-LAST:event_btnNActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "O");
        }
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "P");
        }
    }//GEN-LAST:event_btnPActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "Q");
        }
    }//GEN-LAST:event_btnQActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "R");
        }
    }//GEN-LAST:event_btnRActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "S");
        }
    }//GEN-LAST:event_btnSActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "T");
        }
    }//GEN-LAST:event_btnTActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "U");
        }
    }//GEN-LAST:event_btnUActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "V");
        }
    }//GEN-LAST:event_btnVActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "W");
        }
    }//GEN-LAST:event_btnWActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "X");
        }
    }//GEN-LAST:event_btnXActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "Y");
        }
    }//GEN-LAST:event_btnYActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        if (txfWordleInput.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "Word cannot be longer than 5 letters");
        } else {
            txfWordleInput.setText(txfWordleInput.getText() + "Z");
        }
    }//GEN-LAST:event_btnZActionPerformed

    private void btnCheckWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckWordActionPerformed

        
        String guess = txfWordleInput.getText();
        txaWordleOutput.append(guess + " ");
        
        if (remainingChances > 0){
            JOptionPane.showMessageDialog(this, remainingChances);
            if (guess.length() == 5) {
                String output = "";
                

                    if (word.equalsIgnoreCase(guess)) {
                        JOptionPane.showMessageDialog(this, "Congratulations╰(*°▽°*)╯" + guess + " is correct");
                        this.setVisible(false);
                        remainingChances =0;
                        Score+= 2000;
                        wl.inputScore(txfUsername.getText(), Score);
                        frmScore.setSize(400,450);
                        frmScore.setLocationRelativeTo(null);
                        frmScore.setVisible(true);
                        txfUserNameScore.setText(txfUsername.getText());
                        txfUserNameScore.setEditable(false);
                        txfUserScore.setText(String.valueOf(Score));
                        txfUserScore.setEditable(false);
                    } else{
                        boolean[] matchedPosition = new boolean[word.length()];
                        
                       
                        for(int j=0; j<guess.length();j++)
                        {
                            char letter = guess.charAt(j);
                            if (Character.toUpperCase(word.charAt(j)) == Character.toUpperCase(letter)) {
                                output+= letter + "-green ";
                                Score += 50;
                                matchedPosition[j] = true;
                            } else
                            if(word.toUpperCase().contains(String.valueOf(letter).toUpperCase())) {
                                output += letter +"-grey ";
                                Score+= 25;
                            }else{
                                output+= letter + "-red ";
                                Score+= -25;
                            }
                            
                        }
                    }
                
                txaWordleOutput.append(output + "\n");
                txfWordleInput.setText("");
               
                
                remainingChances--;
            } else {
                JOptionPane.showMessageDialog(this, "You should input a 5 letter word");
            }
           
        }else
        {
            JOptionPane.showMessageDialog(this,"No more chances left! Game Over\nThe correct word is " + word );
            wl.inputScore(txfUsername.getText(), Score);
            frmScore.setSize(400,450);
            frmScore.setLocationRelativeTo(null);
            frmScore.setVisible(true);
            txfUserNameScore.setText(txfUsername.getText());
            txfUserNameScore.setEditable(false);
            txfUserScore.setText(String.valueOf(Score));
            txfUserScore.setEditable(false);
        }
    }//GEN-LAST:event_btnCheckWordActionPerformed

    private void btnNoAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoAccActionPerformed
        frmLogin.setVisible(false);
        
        frmRegister.setLocationRelativeTo(this);
        frmRegister.setSize(400,400);
        frmRegister.setVisible(true);
        JOptionPane.showMessageDialog(this,"Your username must be atleast 5 characters and contain a number\nPassword should be 8 characters long and have a number and special character");
    }//GEN-LAST:event_btnNoAccActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String regiUsername = txfUNameRegister.getText();
        String password = pasUPassRegi.getText();
        String confirmPassword= pasUPassConfirmRegi.getText();
        
        if(regiUsername.length()>=5 &&password.length()>=8&&wl.contains3Numbers(password) && wl.contains3Numbers(regiUsername) == true && password.equals(confirmPassword))
        {
            wl.Register(regiUsername, password);
            JOptionPane.showMessageDialog(this, "Registration successful. \nDo Not Forget your username and password as you login\n(It is imperative)");
            frmLogin.setVisible(true);
            frmRegister.setVisible(false);
            System.out.println("true");
        }else if(regiUsername.length()<5 || wl.contains3Numbers(regiUsername)== false)
        {
            JOptionPane.showMessageDialog(this, "Username must be longer than 5 characters and contain  three numbers");
        }else if(wl.containsNumberandSpecial(password)== false || password.length()<8)
        {
            JOptionPane.showMessageDialog(this, "Password should have a special character and number and longer than 8 characters");
        }
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txfUserScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUserScoreActionPerformed
        
        
    }//GEN-LAST:event_txfUserScoreActionPerformed

    private void txfUserNameScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUserNameScoreActionPerformed
        
    }//GEN-LAST:event_txfUserNameScoreActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordleInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordleInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordleInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordleInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordleInterface().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCheckWord;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnNoAcc;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JFrame frmLogin;
    private javax.swing.JFrame frmRegister;
    private javax.swing.JFrame frmScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblConPassword;
    private javax.swing.JLabel lblEntPassword;
    private javax.swing.JLabel lblEntUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pasUPassConfirmRegi;
    private javax.swing.JPasswordField pasUPassRegi;
    private javax.swing.JPasswordField pasUserPassword;
    private javax.swing.JTextArea txaWordleOutput;
    private javax.swing.JTextField txfUNameRegister;
    private javax.swing.JTextField txfUserNameScore;
    private javax.swing.JTextField txfUserScore;
    private javax.swing.JTextField txfUsername;
    private javax.swing.JTextField txfWordleInput;
    // End of variables declaration//GEN-END:variables
}
